language: node_js
node_js:
  - "stable"	
sudo: required
services:
  - mongodb



branches:
  only:
    - master  

install:
  - npm install
  - npm install mongodb
  - npm install mongoose
  - npm install nodemon
  - npm install joi
  - nmp install validator

script:
  - npm build

env:
  - SERVER_IP_ADDRESS=3.17.150.160

after_success:
  - chmod 400 testaws.pem
  - ssh -o "UserKnownHostsFile=/dev/null" -o "StrictHostKeyChecking=no" -i /home/lina/Downloads/testaws.pem ubuntu@ec2-3-17-150-160.us-east-2.compute.amazonaws.com
  - git clone https://github.com/linaAyman/SW-BackEnd.git
  - npm install
  - npm install mongodb
  - npm install mongoose
  - npm install nodemon
  - npm install joi
  - nmp install validator
  - npm run watch
